#!/bin/bash
# define Editor, 'vim'
cd $HOME # Navigate to Home, primarily for WSL
EDITOR="vim"
dotdir="$HOME/git/dot/"
[ -d ${dotdir}Unix/CONFIG/Scripts ] && export PATH=$PATH:${dotdir}Unix/CONFIG/Scripts
	
if [ -f ~/.dir_colors ]; then
	eval `dircolors ~/.dir_colors`
	LS_COLORS=$LS_COLORS:'ow=1;4;93'; export LS_COLORS
fi

#alias ohmyzsh="$EDITOR ~/.oh-my-zsh"

alias bashrc="$EDITOR $HOME/.bashrc"
alias zshconfig="$EDITOR $HOME/.zshrc"
alias zshrc="$EDITOR $HOME/.zshrc"
alias vimrc="$EDITOR $HOME/.vimrc"
alias vrc="$EDITOR $HOME/.vimrc"
#alias fvim="$EDITOR $(ls |fzf)"

alias alrc="$EDITOR $HOME/.Aliases"
alias alconfig="alrc"
alias dd="cd $dotdir"
alias BIN="cd $HOME/.local/bin"

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias grep='grep --color=always'
alias G='| grep'
alias L='| less'

# LS
alias ls='ls -F --color=always' # -F --classify, appends indicator to entires
alias l1='ls -1' # -1, Force output to be one entry per line
alias la='ls -A' # -A, simialr to -a but excludes '.' and '..' entries
alias lA='ls -1A' # ^ ^
alias ll='ls -gA' # -g, like -l but excludes owner
alias l.='ls -d .*' # -d --directory, like directories, not content

alias aG='alias G'
alias cd.='cd ..'
alias c.='cd ..'

cs(){
	cd $@
       	ls
}

#ls(){ ls --colour=always; }
